### ISSUE TITLE
So how can i get the dll working?

### ISSUE THREAD

**Issue by ghost** [Shaxzy/NIXWARE-CSGO#2]
So how can i get the dll inject?
Where can i paste it or when will you make the new version?

**Comment by Shaxzy** [comment]
It's not my cheat.

**Comment by ghost** [comment]
Okey... so who's cheat this is then?

**Comment by Shaxzy** [comment]
"Nixer"
I found his source leaked somewhere and managed to download it before it got taken down.

**Comment by ghost** [comment]
So does it even work and are you using it?
Sorry for questioning everything :D

**Comment by Shaxzy** [comment]
Nah, it does not work. Just decided to upload it in case someone wants to paste features etc. from it

**Comment by Shaxzy** [comment]
https://github.com/Shaxzy/NIXWARE-CSGO/releases/tag/v1.0
