### ISSUE TITLE
i smell something

### ISSUE THREAD

**Issue by jev0n** [Shaxzy/NIXWARE-CSGO#3]
hmmm

nice ip btw
#define IP "35.204.191.243"
#define PORT "1337"

also the cheat seems to be sending and receiving data from multi ips (guess radio channels)

+ the hook checker seem fishy

**Comment by Shaxzy** [comment]
True

**Comment by xevziii** [comment]
wow...

**Comment by Shaxzy** [comment]
New verison is working, no «I smell something»

**Comment by xevziii** [comment]
New version?

**Comment by xevziii** [comment]
Oh yeah but that last one was like a backdoor...

**Comment by Shaxzy** [comment]
This
https://github.com/Shaxzy/NIXWARE-CSGO/releases/tag/v1.0

**Comment by xevziii** [comment]
Okey

**Comment by xevziii** [comment]
But is it vac proof? or i i need to add some junk code?
